### ISSUE TITLE
Update ClojureScript dependencies

### ISSUE THREAD

**Issue by manuel-uberti** [Olical/depot#8]
Hi,

first of all thanks for `depot`, an amazingly simple and efficient tool to keep my projects up-to-date. :+1: 

I was wondering if there was a way to check `shadow-cljs.edn` for outdated dependencies as well. Using `shadow-cljs`, I every CLJS-related dependency in that file, and it would be useful to keep those dependencies updated as well.

**Comment by Olical** [comment]
There's no way right now other than copying the deps section of your `shadow-cljs.edn` to and from a `deps.edn` file. I've never used shadow-cljs so I'm kinda inferring this from skimming some example configuration :sweat_smile:

If it has the _exact_ same structure as `deps.edn` but is just nested inside `shadow-cljs.edn` I suppose there could be a flag that made depot check there as well / instead? If it _is_ the same as `deps.edn` though, why is it in `shadow-cljs.edn` in the first place, wouldn't it make more sense to let one each tool deal with it's own file?

If they're different formats I'd be reluctant to add this features since it's smells "feature creep"-ish to me. What if shadow-cljs falls out of favour and another-shadow-cljs takes the community by storm for example. I'd rather _just_ support `deps.edn` if that's common ground for 90% of the projects being created these days. Open to a discussion though!

**Comment by manuel-uberti** [comment]
From what I see, `deps.edn` stores dependencies as a map, while `shadow-cljs` uses the vector-of-vectors syntax.

Honestly, I've been using `shadow-cljs` since a couple of days so I am not the most expert here. :smile: 

Maybe useful to ping @thheller about this.

**Comment by manuel-uberti** [comment]
Actually, you know what? It *does* make sense to have a different tool taking care of `shadow-cljs`. No sense in over engineering yours.

Thanks again.

**Comment by Olical** [comment]
Yeah, I was probably going to argue that it was out of scope. Thanks for bringing it up though, it's an interesting idea and worth thinking about.
